About Page (Mission Section and Timeline Styled)
ufsasewebmaster/UF-SASE-Website pull request #56
Opened 2024-10-21 21:13 UTC by T-Joseph-Kim

![image](https://github.com/user-attachments/assets/013b569d-0ec5-4d60-9a88-828ce12d3b47)
![image](https://github.com/user-attachments/assets/17cb7308-15db-40a1-8bbe-c82b1ef9082a)

2024-10-21 21:28 UTC, ufsasewebmaster requested changes
See comments

2024-10-21 21:28 UTC, ufsasewebmaster commented on app.config.timestamp_1729437130451.js
Remove this file

2024-10-21 21:28 UTC, ufsasewebmaster commented on client/components/styles/timeline.css
We are using tailwind, not regular CSS. Make sure you're considering the readability and integration of the code.

2024-10-21 21:28 UTC, ufsasewebmaster commented on tailwind.config.cjs
You can define Poppins in the tailwind config instead of here.

2024-10-21 21:30 UTC, ufsasewebmaster commented on client/index.css
You can remove the Poppins fontfamily since it's already in the tailwind config

2024-10-21 23:01 UTC, T-Joseph-Kim commented on client/index.css
In order to do use the font correctly, I will have to leave it in index.css and remove it in tailwind config.

2024-10-22 23:34 UTC, ufsasewebmaster commented on client/index.css
Wait why? We're using tailwind so shouldn't you be able to define it only in the tailwind config?

2024-10-22 23:38 UTC, T-Joseph-Kim commented on client/index.css
I honestly am not sure. There is definitely a way to do it through tailwind config. Index.css allows me to use the font properly with weights. When I import it in tailwind config, the font is always bold which means I'm not actually using it from tailwind config. I will try and figure this out if its better to do it through tailwind config.

2024-10-26 01:03 UTC, T-Joseph-Kim commented
Added contact us form and added many styling changes. Still need a new timeline that incorporates tailwind css.

2024-10-26 06:37 UTC, ufsasewebmaster commented
I fixed some conflicts by merging with sprint-2, but just in case check that everything you made is still present. A couple small things then it will be good:
Make the timeline scrolling a little more intuitive
Host the constitution pdf locally instead of from WP
Fix formatting checks (I forgot to do them)

2024-10-28 19:21 UTC, merged