v1 auth
ufsasewebmaster/UF-SASE-Website pull request #73
Opened 2024-10-30 18:21 UTC by TheBlueSummon

Having trouble with Auth context in ./client/routes/__root.tsx
I should have an auth route already that should like to website/authed
Would be very helpful if someone can look over it and lmk what went wrong

2024-10-31 04:18 UTC, ethanniser requested changes
https://tanstack.com/router/latest/docs/framework/react/guide/authenticated-routes#redirecting

lets try doing somehting like this is the `routes/_authenticated.tsx` layout

then just put all authenticated routes under `routes/_authenticated/<route>.tsx`

2024-10-31 04:18 UTC, ethanniser commented on client/routes/About.tsx
> +export const Route = createFileRoute('/About')({
this should probably be undone...

2024-10-31 04:18 UTC, ethanniser commented on client/routes/Profile.tsx
> +export const Route = createFileRoute('/Profile')({
same thing

2024-11-02 02:24 UTC, ufsasewebmaster commented
Closed because of updated #77. Pretty sure there was a misuderstanding of what files where what when adding the example code (+ branched from main, not sprint-2, outdated)

2024-11-02 02:24 UTC, closed without merging